export enum Routes {
  HOME = '/',
  REGISTER = '/register',
  PROFILE= '/profile',
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  TERMS_AND_CONDITIONS = '/shelf-terms-and-conditions',
  VERIFICATION = '/verification/:token',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password/:jwtToken',
  SHARED_SHELVES = 'shared-shelves',
  TRASH = 'trash',
  FUNCTIONS = 'functions',
  STATISTICS = 'statistics',
  USERS = 'users',
  SHELVES = 'shelves/:shelfId',
  FOLDERS = 'folders/:folderId',
}
