name: Running JUnit tests
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '!frontend/**'
      - '!qa/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '!frontend/**'
      - '!qa/**'
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and run tests - account
        run: mvn  -f ./backend/account/pom.xml clean test
      - name: Build and run tests - gateway
        run: mvn  -f ./backend/gateway/pom.xml clean test
      - name: Build and run tests - file-system
        run: mvn  -f ./backend/file-system/pom.xml clean test
      - name: Build and run tests - shelf-function
        run: mvn  -f ./backend/shelf-function/pom.xml clean test
